#AndroidIDE: enforce UTF-8 & locale for Gradle daemon
#Sat Mar 28 19:13:33 GMT 2026
=\=\=\=\=\=\=
systemProp.user.language=en
systemProp.user.country=US
systemProp.sun.jnu.encoding=UTF-8
systemProp.file.encoding=UTF-8
>>>>>>>=branch 'main' of https\://github.com/LaBestia-Ssj/Mi-LIZ.git
org.gradle.jvmargs=-Dfile.encoding\=UTF-8 -Dsun.jnu.encoding\=UTF-8 -Duser.language\=es -Duser.country\=MX
<<<<<<<=HEAD
